"""Guard the committed reference run against silently drifting from the code and README."""

import hashlib
import json
import re
import unittest
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "results" / "reference"


class ReferenceTests(unittest.TestCase):
    def test_reference_results_were_produced_by_the_current_code(self):
        metadata = json.loads((REFERENCE / "run_metadata.json").read_text())
        self.assertEqual(metadata["status"], "complete")
        current = {p.relative_to(ROOT).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
                   for p in sorted((ROOT / "crypto_volatility").glob("*.py"))}
        self.assertEqual(
            metadata["code_hashes"], current,
            "crypto_volatility/ changed after results/reference was generated; rerun the reference analysis "
            "(a CRLF checkout also changes the hashes: .gitattributes pins LF line endings)",
        )

    def test_reference_verification_summary_is_consistent(self):
        metadata = json.loads((REFERENCE / "run_metadata.json").read_text())
        summary = json.loads((REFERENCE / "validation_summary.json").read_text())
        self.assertEqual(summary["status"], "passed")
        self.assertEqual(summary["scored_prediction_rows"], metadata["scored_prediction_rows"])
        self.assertEqual(summary["source_files_verified"], len(metadata["input_hashes"]))
        self.assertEqual(summary["code_files_verified"], len(metadata["code_hashes"]))

    def test_readme_quotes_the_reference_scores(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        macro = pd.read_csv(REFERENCE / "macro_metrics.csv")
        daily = macro[macro["sample"].eq("daily_origins")].set_index("model")
        for model in ("Persistence", "Historical90", "Ridge"):
            self.assertIn(f"{100 * daily.loc[model, 'macro_mae']:.2f}", readme, model)
        self.assertIn(f"**{int(daily.loc['Ridge', 'n_assets'])} assets**", readme)
        self.assertIn(f"**{int(daily.loc['Ridge', 'n_scored']):,} asset-origin observations per model**", readme)
        validation = pd.read_csv(REFERENCE / "data_validation.csv")
        accepted = validation[validation["status"].eq("accepted")]
        self.assertIn(f"**{len(accepted)} asset histories", readme)
        self.assertIn(f"{int(accepted['missing_days'].sum())} missing calendar days", readme)
        self.assertIn(f"{int(accepted['invalid_close_rows'].sum())} nonpositive closes", readme)
        self.assertIn(f"{int(accepted['source_rows'].sum()):,} source price rows", readme)

    def test_reference_directory_holds_only_documented_outputs(self):
        present = {p.relative_to(REFERENCE).as_posix() for p in REFERENCE.rglob("*") if p.is_file()}
        documented = {
            "report.md", "run_metadata.json", "validation_summary.json", "data_validation.csv",
            "data_quality_events.csv", "summary_statistics.csv", "backtest_predictions.csv",
            "backtest_metrics.csv", "macro_metrics.csv", "next_forecasts.csv", "model_status.json",
            "common_window_statistics.csv", "common_window_indexed_close.csv", "common_window_log_returns.csv",
            "common_window_volatility_30.csv", "common_window_return_correlations.csv",
            "common_window_correlation_pair_counts.csv", "common_window_normalized_reported_volume.csv",
        } | {f"figures/{name}.png" for name in ("indexed_prices", "rolling_volatility", "return_distributions",
                                                "return_correlations", "normalized_volume", "forecast_comparison")}
        # The 17 MB history table is regenerated by every run and stays out of Git.
        self.assertEqual(present - {"validated_daily_history.csv"}, documented)
        report = (REFERENCE / "report.md").read_text(encoding="utf-8")
        for link in re.findall(r"\]\(([^)]+)\)", report):
            if not link.startswith("http"):
                self.assertTrue((REFERENCE / link).exists(), f"report.md links to a missing file: {link}")


if __name__ == "__main__":
    unittest.main()
